# Custom vars
# -------------------------

current_version:  1.0.0
name: 			  Seahull

# Main Logo
# -------------------------

logo_regular: "media/logo/logo_regular.png" 
logo_small_devices: "media/logo/logo_small.png"


# Main Navigation Links
# -------------------------

navbar_links:
  - title: "Home"
    url: "#image-hero"
  - title: "Features"
    url: "#features"
  - title: "Services"
    url: "#services"
  - title: "Work"
    url: "#work"    
  - title: "Pricing Tables"
    url: "#pricing-tables"
  - title: "Contact"
    url: "#contact"

# Navigation Background Color. 
# Options: caribbean-green, summer-sky, golden-poppy, deep-carmine-pink
navbar_color: "caribbean-green"

# Image Hero
# -------------------------

title:            "Seahull"
tagline:      	  "Welcome to Seahull Boats"

# Features Thumbs
# -------------------------

features_thumbs:
  - title: "Built Tough"
    icon: "gavel"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Lightweight"
    icon: "dashboard"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Precisely Engineered"
    icon: "gears"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Unique Design"
    icon: "file-image-o"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Safe and Sound"
    icon: "anchor"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Standards Compliant"
    icon: "check-square-o"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Ships Worldwide"
    icon: "globe"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."
  - title: "Eco Friendly"
    icon: "paw"
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta ipsam a illum, ducimus quod impedit architecto distinctio dolorem amet dignissimos ad corrupti! Fugit aut earum in sit, placeat quis consequatur."

# Blockquote
# -------------------------

blockquote: 
   text: "We develop online marketing solutions that help enterprises accurately identify the consumers that truly need their services."
   tagline: "Serving the community since 2014"
   button_text: "Read More"
   button_url: "#_"

# Services
# -------------------------

services:
 - title: "Front-End Development"
   icon: "desktop"
   description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
 - title: "iOS Development"
   icon: "apple"
   description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."
 - title: "UI/UX Design"
   icon: "magic"
   description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni tenetur officiis vel aspernatur. Quidem eligendi sequi veritatis vel recusandae porro maxime corporis id, deleniti harum alias asperiores soluta unde aliquam."      

# Work Mosaic
# -------------------------

work_thumbs:
 - title: "Maxime Corporis Set"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-01.jpg"
 - title: "Veritatis Vel Recusandae"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-02.jpg"
 - title: "Consectetur Adipisicing"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-03.jpg"
 - title: "Asperiores Soluta"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-04.jpg"
 - title: "Officiis Aspernatur"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-05.jpg"   
 - title: "Soluta Asperiores"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-06.jpg"
 - title: "Adipisicing Consectetur"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-07.jpg"
 - title: "Maxime Corporis Set"
   description: "Fugit aut earum in sit, placeat quis consequatur."
   url: "#_"
   image: "media/img/work-08.jpg"

# Contact
# -------------------------

contact:
   latitude: "-36.836836"
   longitude: "174.759669"
   marker_title: "Seahull"
   marker_address: "Auckland, New Zealand"
   phone_number: "+64 27 573 7861"
   email_address: "chris.cadag@gmail.com"

# Configuration
# -------------------------

# Dependencies
pygments: 		  false

# Permalinks
permalink: 		  none

# Server
destination: 	  ../kunstnerisk
exclude: 		  [".gitignore", "Gruntfile.js", "node_modules", "package.json"]
port: 			  1984